site_name: p4-fs

theme:
  name: material
  #name: mkdocs
  # custom_dir: material

  # 404 page
  static_templates:
  - 404.html
    
  navigation_depth: 3
  
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
    # - navigation.sections
    - navigation.tabs
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

plugins:
  - search
#  - git-revision-date-localized

nav:
  - exp1: interpretation.md
  - exp2: consistency.md
  - cmd: lite.md    
 # - /wsl: wsl.md
  #- Device:
   # - Hikey: devices/hikey.md
    #- Odroid: devices/odroid.md
  #- /dump: dump.md
